name: Sync

on:
  workflow_dispatch: # on button click
  schedule:
  - cron: "0 */6 * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v2
      with:
        repository: greatghoul/lightjiao.github.io
    - name: Sync files
      # You may pin to the exact commit or the version.
      # uses: denis-tingaikin/sync-files@7cf3a71d4530214ecee324faf12cf884a275d366
      uses: denis-tingaikin/sync-files@v1.0.2
      with:
        git-author-email: greatghoul@gmail.com
        git-author-name: greatghoul
        sync-repository: lightjiao/lightjiao.github.io
        sync-branch-name: master
        result-branch-name: master
        allow-files-pattern: "Blogs/.*"
